name: C/C++ CI

on: [push]

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build project
      run: |
        cmake .
        cmake --build .

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: |
        cmake .
        cmake --build . --config Release
        cmake --build . --config Debug